[2025-10-31T23:00:01.288+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:00:01.306+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_consumer scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:00:01.310+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_consumer scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:00:01.310+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-10-31T23:00:01.316+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_consumer> on 2025-10-31 15:00:00+00:00
[2025-10-31T23:00:01.323+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1806) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:00:01.325+0700] {standard_task_runner.py:63} INFO - Started process 1818 to run task
[2025-10-31T23:00:01.328+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_consumer', 'scheduled__2025-10-31T15:00:00+00:00', '--job-id', '384', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmpghnawuz0']
[2025-10-31T23:00:01.331+0700] {standard_task_runner.py:91} INFO - Job 384: Subtask start_vehicle_consumer
[2025-10-31T23:00:01.389+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_consumer scheduled__2025-10-31T15:00:00+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:00:01.463+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T15:00:00+00:00'
[2025-10-31T23:00:01.465+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:00:01.465+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:00:01.466+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m /opt/***/projects/vehicle_count/scripts/run_consumer.sh"']
[2025-10-31T23:00:01.479+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:00:01.488+0700] {subprocess.py:93} INFO - timeout: failed to run command ‘/opt/***/projects/vehicle_count/scripts/run_consumer.sh’: Permission denied
[2025-10-31T23:00:01.489+0700] {subprocess.py:97} INFO - Command exited with return code 126
[2025-10-31T23:00:01.490+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:00:01.502+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2025-10-31T23:00:01.505+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_consumer, execution_date=20251031T150000, start_date=20251031T160001, end_date=20251031T160001
[2025-10-31T23:00:01.514+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 384 for task start_vehicle_consumer (Bash command failed. The command returned a non-zero exit code 126.; 1818)
[2025-10-31T23:00:01.539+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:00:01.558+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:00:01.559+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-10-31T23:20:30.749+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:20:30.765+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_consumer scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:20:30.769+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_consumer scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:20:30.769+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-10-31T23:20:30.777+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_consumer> on 2025-10-31 15:00:00+00:00
[2025-10-31T23:20:30.782+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2606) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:20:30.783+0700] {standard_task_runner.py:63} INFO - Started process 2611 to run task
[2025-10-31T23:20:30.784+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_consumer', 'scheduled__2025-10-31T15:00:00+00:00', '--job-id', '445', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmpx5ttkubq']
[2025-10-31T23:20:30.786+0700] {standard_task_runner.py:91} INFO - Job 445: Subtask start_vehicle_consumer
[2025-10-31T23:20:30.831+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_consumer scheduled__2025-10-31T15:00:00+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:20:30.895+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T15:00:00+00:00'
[2025-10-31T23:20:30.896+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:20:30.897+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:20:30.897+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m /opt/***/projects/vehicle_count/scripts/run_consumer.sh"']
[2025-10-31T23:20:30.908+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:20:30.915+0700] {subprocess.py:93} INFO - timeout: failed to run command ‘/opt/***/projects/vehicle_count/scripts/run_consumer.sh’: Permission denied
[2025-10-31T23:20:30.916+0700] {subprocess.py:97} INFO - Command exited with return code 126
[2025-10-31T23:20:30.916+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:20:30.927+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2025-10-31T23:20:30.931+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_consumer, execution_date=20251031T150000, start_date=20251031T162030, end_date=20251031T162030
[2025-10-31T23:20:30.939+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 445 for task start_vehicle_consumer (Bash command failed. The command returned a non-zero exit code 126.; 2611)
[2025-10-31T23:20:30.957+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:20:30.987+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:20:30.988+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
