[2025-10-31T23:22:37.490+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:22:37.505+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 manual__2025-10-31T16:20:34.210157+00:00 [queued]>
[2025-10-31T23:22:37.508+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 manual__2025-10-31T16:20:34.210157+00:00 [queued]>
[2025-10-31T23:22:37.508+0700] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2025-10-31T23:22:37.514+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_producer_cam2> on 2025-10-31 16:20:34.210157+00:00
[2025-10-31T23:22:37.519+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:22:37.521+0700] {standard_task_runner.py:63} INFO - Started process 2895 to run task
[2025-10-31T23:22:37.526+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_producer_cam2', 'manual__2025-10-31T16:20:34.210157+00:00', '--job-id', '465', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmpy6pudgn3']
[2025-10-31T23:22:37.529+0700] {standard_task_runner.py:91} INFO - Job 465: Subtask start_vehicle_producer_cam2
[2025-10-31T23:22:37.565+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 manual__2025-10-31T16:20:34.210157+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:22:37.622+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_producer_cam2' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T16:20:34.210157+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T16:20:34.210157+00:00'
[2025-10-31T23:22:37.623+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:22:37.624+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:22:37.624+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/vehicle_count/scripts/run_producer_cam2.sh"']
[2025-10-31T23:22:37.635+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:22:37.644+0700] {subprocess.py:93} INFO - [Producer-CAM2] üèçÔ∏è Starting Vehicle Kafka Producer (Camera 2)...
[2025-10-31T23:22:37.666+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T23:22:37.667+0700] {subprocess.py:93} INFO -   File "/opt/***/projects/vehicle_count/scripts/vehicle_producer_single.py", line 13, in <module>
[2025-10-31T23:22:37.667+0700] {subprocess.py:93} INFO -     import cv2
[2025-10-31T23:22:37.667+0700] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'cv2'
[2025-10-31T23:22:37.670+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:22:37.671+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:22:37.681+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:22:37.685+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_producer_cam2, execution_date=20251031T162034, start_date=20251031T162237, end_date=20251031T162237
[2025-10-31T23:22:37.693+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 465 for task start_vehicle_producer_cam2 (Bash command failed. The command returned a non-zero exit code 1.; 2895)
[2025-10-31T23:22:37.735+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:22:37.763+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:22:37.764+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
