[2025-10-31T23:10:44.090+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:10:44.107+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:10:44.111+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:10:44.111+0700] {taskinstance.py:2303} INFO - Starting attempt 4 of 6
[2025-10-31T23:10:44.117+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_producer_cam2> on 2025-10-31 15:00:00+00:00
[2025-10-31T23:10:44.123+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2206) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:10:44.124+0700] {standard_task_runner.py:63} INFO - Started process 2208 to run task
[2025-10-31T23:10:44.125+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_producer_cam2', 'scheduled__2025-10-31T15:00:00+00:00', '--job-id', '431', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmpkejg9t_e']
[2025-10-31T23:10:44.127+0700] {standard_task_runner.py:91} INFO - Job 431: Subtask start_vehicle_producer_cam2
[2025-10-31T23:10:44.172+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 scheduled__2025-10-31T15:00:00+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:10:44.237+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_producer_cam2' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T15:00:00+00:00'
[2025-10-31T23:10:44.239+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:10:44.240+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:10:44.240+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/vehicle_count/scripts/run_producer_cam2.sh"']
[2025-10-31T23:10:44.250+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:10:44.258+0700] {subprocess.py:93} INFO - [Producer-CAM2] üèçÔ∏è Starting Vehicle Kafka Producer (Camera 2)...
[2025-10-31T23:10:44.279+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T23:10:44.280+0700] {subprocess.py:93} INFO -   File "/opt/***/projects/vehicle_count/scripts/vehicle_producer_single.py", line 13, in <module>
[2025-10-31T23:10:44.280+0700] {subprocess.py:93} INFO -     import cv2
[2025-10-31T23:10:44.280+0700] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'cv2'
[2025-10-31T23:10:44.283+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:10:44.284+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:10:44.296+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:10:44.299+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_producer_cam2, execution_date=20251031T150000, start_date=20251031T161044, end_date=20251031T161044
[2025-10-31T23:10:44.308+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 431 for task start_vehicle_producer_cam2 (Bash command failed. The command returned a non-zero exit code 1.; 2208)
[2025-10-31T23:10:44.341+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:10:44.360+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:10:44.361+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
