[2025-10-31T23:14:47.010+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:14:47.025+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:14:47.028+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:14:47.028+0700] {taskinstance.py:2303} INFO - Starting attempt 6 of 6
[2025-10-31T23:14:47.033+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_producer_cam2> on 2025-10-31 15:00:00+00:00
[2025-10-31T23:14:47.037+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2351) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:14:47.038+0700] {standard_task_runner.py:63} INFO - Started process 2353 to run task
[2025-10-31T23:14:47.040+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_producer_cam2', 'scheduled__2025-10-31T15:00:00+00:00', '--job-id', '437', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmpi25rmlvm']
[2025-10-31T23:14:47.043+0700] {standard_task_runner.py:91} INFO - Job 437: Subtask start_vehicle_producer_cam2
[2025-10-31T23:14:47.082+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 scheduled__2025-10-31T15:00:00+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:14:47.137+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_producer_cam2' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T15:00:00+00:00'
[2025-10-31T23:14:47.138+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:14:47.139+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:14:47.140+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/vehicle_count/scripts/run_producer_cam2.sh"']
[2025-10-31T23:14:47.148+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:14:47.156+0700] {subprocess.py:93} INFO - [Producer-CAM2] üèçÔ∏è Starting Vehicle Kafka Producer (Camera 2)...
[2025-10-31T23:14:47.180+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T23:14:47.181+0700] {subprocess.py:93} INFO -   File "/opt/***/projects/vehicle_count/scripts/vehicle_producer_single.py", line 13, in <module>
[2025-10-31T23:14:47.181+0700] {subprocess.py:93} INFO -     import cv2
[2025-10-31T23:14:47.181+0700] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'cv2'
[2025-10-31T23:14:47.184+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:14:47.184+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:14:47.196+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:14:47.199+0700] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_producer_cam2, execution_date=20251031T150000, start_date=20251031T161447, end_date=20251031T161447
[2025-10-31T23:14:47.206+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 437 for task start_vehicle_producer_cam2 (Bash command failed. The command returned a non-zero exit code 1.; 2353)
[2025-10-31T23:14:47.255+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:14:47.273+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:14:47.274+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
