[2025-10-31T22:35:06.932+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T22:35:06.954+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_consumer manual__2025-10-31T15:35:05.801684+00:00 [queued]>
[2025-10-31T22:35:06.960+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_consumer manual__2025-10-31T15:35:05.801684+00:00 [queued]>
[2025-10-31T22:35:06.961+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-10-31T22:35:06.969+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_consumer> on 2025-10-31 15:35:05.801684+00:00
[2025-10-31T22:35:06.978+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1007) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T22:35:06.980+0700] {standard_task_runner.py:63} INFO - Started process 1018 to run task
[2025-10-31T22:35:06.982+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_consumer', 'manual__2025-10-31T15:35:05.801684+00:00', '--job-id', '296', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmpsg3b68r2']
[2025-10-31T22:35:06.985+0700] {standard_task_runner.py:91} INFO - Job 296: Subtask start_vehicle_consumer
[2025-10-31T22:35:07.078+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_consumer manual__2025-10-31T15:35:05.801684+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T22:35:07.174+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:35:05.801684+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T15:35:05.801684+00:00'
[2025-10-31T22:35:07.176+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T22:35:07.177+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T22:35:07.178+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m /opt/***/projects/vehicle_count/scripts/run_consumer.sh"']
[2025-10-31T22:35:07.202+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T22:35:07.213+0700] {subprocess.py:93} INFO - timeout: failed to run command ‘/opt/***/projects/vehicle_count/scripts/run_consumer.sh’: Permission denied
[2025-10-31T22:35:07.226+0700] {subprocess.py:97} INFO - Command exited with return code 126
[2025-10-31T22:35:07.239+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T22:35:07.265+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2025-10-31T22:35:07.269+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_consumer, execution_date=20251031T153505, start_date=20251031T153506, end_date=20251031T153507
[2025-10-31T22:35:07.281+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 296 for task start_vehicle_consumer (Bash command failed. The command returned a non-zero exit code 126.; 1018)
[2025-10-31T22:35:07.318+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T22:35:07.362+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T22:35:07.366+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
