[2025-10-31T23:12:37.768+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:12:37.783+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam1 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:12:37.786+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam1 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:12:37.787+0700] {taskinstance.py:2303} INFO - Starting attempt 6 of 7
[2025-10-31T23:12:37.793+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_producer_cam1> on 2025-10-31 15:00:00+00:00
[2025-10-31T23:12:37.798+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2272) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:12:37.800+0700] {standard_task_runner.py:63} INFO - Started process 2274 to run task
[2025-10-31T23:12:37.801+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_producer_cam1', 'scheduled__2025-10-31T15:00:00+00:00', '--job-id', '433', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmp8_ts05cj']
[2025-10-31T23:12:37.805+0700] {standard_task_runner.py:91} INFO - Job 433: Subtask start_vehicle_producer_cam1
[2025-10-31T23:12:37.851+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam1 scheduled__2025-10-31T15:00:00+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:12:37.919+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_producer_cam1' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T15:00:00+00:00'
[2025-10-31T23:12:37.920+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:12:37.921+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:12:37.922+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/vehicle_count/scripts/run_producer_cam1.sh"']
[2025-10-31T23:12:37.933+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:12:37.942+0700] {subprocess.py:93} INFO - [Producer-CAM1] ðŸš— Starting Vehicle Kafka Producer (Camera 1)...
[2025-10-31T23:12:37.963+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T23:12:37.964+0700] {subprocess.py:93} INFO -   File "/opt/***/projects/vehicle_count/scripts/vehicle_producer_single.py", line 13, in <module>
[2025-10-31T23:12:37.964+0700] {subprocess.py:93} INFO -     import cv2
[2025-10-31T23:12:37.964+0700] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'cv2'
[2025-10-31T23:12:37.967+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:12:37.967+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:12:37.977+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:12:37.980+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_producer_cam1, execution_date=20251031T150000, start_date=20251031T161237, end_date=20251031T161237
[2025-10-31T23:12:37.987+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 433 for task start_vehicle_producer_cam1 (Bash command failed. The command returned a non-zero exit code 1.; 2274)
[2025-10-31T23:12:38.015+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:12:38.032+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:12:38.033+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
