[2025-10-31T22:58:53.876+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T22:58:53.893+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_consumer manual__2025-10-31T15:58:52.637042+00:00 [queued]>
[2025-10-31T22:58:53.897+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_consumer manual__2025-10-31T15:58:52.637042+00:00 [queued]>
[2025-10-31T22:58:53.897+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-10-31T22:58:53.904+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_consumer> on 2025-10-31 15:58:52.637042+00:00
[2025-10-31T22:58:53.909+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1753) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T22:58:53.910+0700] {standard_task_runner.py:63} INFO - Started process 1759 to run task
[2025-10-31T22:58:53.912+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_consumer', 'manual__2025-10-31T15:58:52.637042+00:00', '--job-id', '377', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmpa01rcd_0']
[2025-10-31T22:58:53.915+0700] {standard_task_runner.py:91} INFO - Job 377: Subtask start_vehicle_consumer
[2025-10-31T22:58:53.963+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_consumer manual__2025-10-31T15:58:52.637042+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T22:58:54.027+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:58:52.637042+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T15:58:52.637042+00:00'
[2025-10-31T22:58:54.030+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T22:58:54.030+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T22:58:54.031+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m /opt/***/projects/vehicle_count/scripts/run_consumer.sh"']
[2025-10-31T22:58:54.042+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T22:58:54.049+0700] {subprocess.py:93} INFO - timeout: failed to run command ‘/opt/***/projects/vehicle_count/scripts/run_consumer.sh’: Permission denied
[2025-10-31T22:58:54.049+0700] {subprocess.py:97} INFO - Command exited with return code 126
[2025-10-31T22:58:54.050+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T22:58:54.061+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2025-10-31T22:58:54.064+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_consumer, execution_date=20251031T155852, start_date=20251031T155853, end_date=20251031T155854
[2025-10-31T22:58:54.073+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 377 for task start_vehicle_consumer (Bash command failed. The command returned a non-zero exit code 126.; 1759)
[2025-10-31T22:58:54.084+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T22:58:54.103+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T22:58:54.104+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
