[2025-10-31T23:25:57.931+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:25:57.945+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam1 manual__2025-10-31T16:20:34.210157+00:00 [queued]>
[2025-10-31T23:25:57.948+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam1 manual__2025-10-31T16:20:34.210157+00:00 [queued]>
[2025-10-31T23:25:57.948+0700] {taskinstance.py:2303} INFO - Starting attempt 4 of 6
[2025-10-31T23:25:57.954+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_producer_cam1> on 2025-10-31 16:20:34.210157+00:00
[2025-10-31T23:25:57.959+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4270) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:25:57.960+0700] {standard_task_runner.py:63} INFO - Started process 4272 to run task
[2025-10-31T23:25:57.961+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_producer_cam1', 'manual__2025-10-31T16:20:34.210157+00:00', '--job-id', '483', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmp_c4kh53q']
[2025-10-31T23:25:57.963+0700] {standard_task_runner.py:91} INFO - Job 483: Subtask start_vehicle_producer_cam1
[2025-10-31T23:25:57.999+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam1 manual__2025-10-31T16:20:34.210157+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:25:58.055+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_producer_cam1' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T16:20:34.210157+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T16:20:34.210157+00:00'
[2025-10-31T23:25:58.057+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:25:58.057+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:25:58.058+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/vehicle_count/scripts/run_producer_cam1.sh"']
[2025-10-31T23:25:58.068+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:25:58.076+0700] {subprocess.py:93} INFO - [Producer-CAM1] ðŸš— Starting Vehicle Kafka Producer (Camera 1)...
[2025-10-31T23:25:58.338+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T23:25:58.339+0700] {subprocess.py:93} INFO -   File "/opt/***/projects/vehicle_count/scripts/vehicle_producer_single.py", line 19, in <module>
[2025-10-31T23:25:58.340+0700] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-10-31T23:25:58.340+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/__init__.py", line 23, in <module>
[2025-10-31T23:25:58.340+0700] {subprocess.py:93} INFO -     from kafka.consumer import KafkaConsumer
[2025-10-31T23:25:58.340+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/consumer/__init__.py", line 3, in <module>
[2025-10-31T23:25:58.341+0700] {subprocess.py:93} INFO -     from kafka.consumer.group import KafkaConsumer
[2025-10-31T23:25:58.341+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/consumer/group.py", line 13, in <module>
[2025-10-31T23:25:58.341+0700] {subprocess.py:93} INFO -     from kafka.consumer.fetcher import Fetcher
[2025-10-31T23:25:58.342+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/consumer/fetcher.py", line 19, in <module>
[2025-10-31T23:25:58.342+0700] {subprocess.py:93} INFO -     from kafka.record import MemoryRecords
[2025-10-31T23:25:58.342+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/record/__init__.py", line 1, in <module>
[2025-10-31T23:25:58.343+0700] {subprocess.py:93} INFO -     from kafka.record.memory_records import MemoryRecords, MemoryRecordsBuilder
[2025-10-31T23:25:58.343+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/record/memory_records.py", line 27, in <module>
[2025-10-31T23:25:58.343+0700] {subprocess.py:93} INFO -     from kafka.record.legacy_records import LegacyRecordBatch, LegacyRecordBatchBuilder
[2025-10-31T23:25:58.343+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/record/legacy_records.py", line 50, in <module>
[2025-10-31T23:25:58.343+0700] {subprocess.py:93} INFO -     from kafka.codec import (
[2025-10-31T23:25:58.344+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/codec.py", line 9, in <module>
[2025-10-31T23:25:58.344+0700] {subprocess.py:93} INFO -     from kafka.vendor.six.moves import range
[2025-10-31T23:25:58.344+0700] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka.vendor.six.moves'
[2025-10-31T23:25:58.365+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:25:58.365+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:25:58.377+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:25:58.381+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_producer_cam1, execution_date=20251031T162034, start_date=20251031T162557, end_date=20251031T162558
[2025-10-31T23:25:58.392+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 483 for task start_vehicle_producer_cam1 (Bash command failed. The command returned a non-zero exit code 1.; 4272)
[2025-10-31T23:25:58.416+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:25:58.436+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:25:58.437+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
